---
- name: format volume and mount
  hosts: server
  remote_user: ubuntu
  become: yes

  tasks:
  - name: format volume
    filesystem:
      fstype: ext4
      dev: /dev/vdc

  - name: create mount dir
    file:
      path: /mnt/storage
      state: directory

  - name: mount volume
    mount:
      path: /mnt/storage
      src: /dev/vdc
      fstype: ext4
      state: mounted

  - name: create mount dir
    file:
      path: /mnt/storage
      state: directory
      mode: 0777
